# Generated by Django 5.1.3 on 2025-01-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_id_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/blog/images/'),
        ),
    ]
